name: 'Latest Feed'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  readme:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feed.outputs.changed }}
      items: ${{ steps.feed.outputs.items }}
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: 'https://okhk.net/feed'
          file: 'README.md'
          timezone: 'Asia/Shanghai'
          retry: 5
          retry_backoff: 15
      - name: push to master
        if: steps.feed.outputs.changed == true
        id: commit
        uses: sarisia/actions-commit@master
        with:
          message: "update feed"        
